### ISSUE TITLE
Using --help results in a error code != 0

### ISSUE THREAD

**Issue by nicwise** [honeycombio/honeyvent#19]
https://github.com/honeycombio/honeyvent/blob/d7a45bd2586f5d60e395b8d8cf1743cb105c7f9f/main.go#L44

I use `honeyvent --help` in container builds to make sure the thing I just installed works. Well, I use it for everything else, but honeyvent says this is an error 1, and the container build fails. So I have no way to check if the binary I downloaded works or not.

Honeymarker got it right:

https://github.com/honeycombio/honeymarker/blob/main/main.go#L90-L94

I'ld do a PR, but I know _zero_ Go :(

**Comment by vreynolds** [comment]
Nice catch @nicwise ! A PR would be greatly appreciated. 🙏

**Comment by nicwise** [comment]
One moment @vreynolds - off to learn Go...

(seriously, I've not used it at all)
