### ISSUE TITLE
GitHub Release v.1.1.1 only contains sources and linux-amd64 binary 

### ISSUE THREAD

**Issue by jpluscplusm** [honeycombio/honeyvent#51]
So .. if version v1.1.1 intended to stop releasing binaries for darwin, linux-arm64 and linux-386, I certainly couldn't see it being mentioned in the changelog!

If this is intentional, of course please just close this :-)

**Comment by MikeGoldsmith** [comment]
Interesting, this was not intentional.

Doh 😞 
`-d, --draft` https://cli.github.com/manual/gh_release_create

**Comment by MikeGoldsmith** [comment]
Fixed - we'll process a new release soon. Thanks for raising @jpluscplusm 👍🏻
